version: '3.7'
services:

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wtw
      POSTGRES_PASSWORD: wtw
      POSTGRES_DB: wtw
    volumes:
      - storage_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  storage_db: