name: web

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:


jobs:
  lint:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # if: ${{ !env.ACT }}
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - 
      name: Run linter
      uses: github/super-linter@v3
      env:
        # VALIDATE_ALL_CODEBASE: false
        # VALIDATE_TYPESCRIPT_ES: false
        # VALIDATE_TSX: false
        # TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ACTIONS_RUNNER_DEBUG: false
        DEFAULT_WORKSPACE: apps/web
        JAVASCRIPT_DEFAULT_STYLE: prettier
        VALIDATE_JAVASCRIPT_STANDARD: false
        VALIDATE_TYPESCRIPT_STANDARD: false

  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Gitlab
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: registry.gitlab.com/nevax/wtw/wtw-web # list of Docker images to use as base name for tags
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
    -
      name: Build and push base
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/web/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=registry,ref=registry.gitlab.com/nevax/wtw/wtw-web:latest
        cache-to: type=inline
        build-args: |
            "REACT_APP_KEYCLOAK_REALM=${{ secrets.REACT_APP_KEYCLOAK_REALM }}"
            "REACT_APP_KEYCLOAK_URL=${{ secrets.REACT_APP_KEYCLOAK_URL }}"
            "REACT_APP_KEYCLOAK_CLIENT_ID=${{ secrets.REACT_APP_KEYCLOAK_CLIENT_ID }}"
